Month 7/step 1
productmap/react-stellar-burger pull request #1
Opened 2023-07-20 15:39 UTC by productmap

2023-07-20 17:50 UTC, andryxxa93 requested changes
Здравствуйте! Проделана большая работа 👍 

Что понравилось:
- Проект соответствует макету
- Хороший `codestyle` - логичный и понятный код

Однако есть пару моментов, которые необходимо исправить, чтобы работа была принята.

Необходимо исправить:
- Все компоненты с пропсами должны иметь `propTypes` с типизацией этих пропсов
- Добавьте `isRequired` у полей объекта `ingredientPropType ` и propTypes компонентов

Более подробно описание проблемы смотрите комментарии в pull request.

В pull request вы так же найдете комментарии с рекомендациями как **можно улучшить** код. Их делать не обязательно, однако в будущем они могут помочь избежать ошибок и сделать код лучше.

**Напомню, чтобы работа была принята нужно исправить все замечания помеченные как **необходимо исправить**.

Пожалуйста, проверьте работоспособность проекта и наличие возможных ошибок в консоли браузера (кнопка F12) перед отправкой на ревью. 

Удачных правок!

2023-07-20 17:50 UTC, andryxxa93 commented on src/utils/prop-types.js
> +  name: PropTypes.string,
**Надо исправить**

в описании propTypes полей объекта так же нужно указывать .isRequired у пропсов, без этого не контролируется, что поле передается

Проверьте во всем проекте

2023-07-20 17:50 UTC, andryxxa93 commented on src/components/app/app.jsx
> +  ingredients.propTypes = {
**Необходимо исправить**
propTypes необходимо указывать у компонентов. Они нужны для описания пропсов.

Например
```
BurgerConstructor.propTypes = {
   cart: ....,
  ingredient: ingredientPropType.isRequired,
}
```

2023-07-20 17:50 UTC, andryxxa93 commented on src/components/app/app.jsx
> +      <Constructor ingredients={ingredients} cart={cart} />
**Можно лучше**
В компоненте прослойке между App и конструктором со списком ингредиентов нет нужды, он не выполняет никакой функции, его верстку можно объявить прям в App.

2023-07-21 15:41 UTC, andryxxa93 requested changes
**Необходимо исправить**
- `ingredients` не является компонентом - у него не может быть `propTypes`
- `propTypes` необходимо объявлять вне компонента

Промежуточная работа принята. Вы можете приступать к финальному этапу сдачи работы.

Удачи!

2023-07-21 15:41 UTC, andryxxa93 commented on src/components/burger-ingredients/ingredients-group/ingredients-group.jsx
> +  IngredientsGroup.propTypes = {
**Необходимо исправить**
propTypes необходимо объявлять вне компонента

2023-07-21 15:41 UTC, andryxxa93 commented on src/components/app/app.jsx
> +  ingredients.propTypes = {
**Необходимо исправить**
`ingredients` не является компонентом - у него не может быть `propTypes`

2023-07-21 16:04 UTC, productmap commented on src/components/burger-ingredients/ingredients-group/ingredients-group.jsx
> +  IngredientsGroup.propTypes = {
В данном случае если вынести то будет оибка, так как проверка будет до объявления компонента.

2023-08-02 20:24 UTC, andryxxa93 commented on src/components/burger-ingredients/ingredients-group/ingredients-group.jsx
> +  IngredientsGroup.propTypes = {
Вы можете вынести из компонента, но объявить propTypes после его объявления (под компонентом)

2023-12-29 12:50 UTC, merged